# Generated by Django 5.0.6 on 2024-05-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('term', 'Term Loan'), ('over_draft', 'Over Draft')], default='term')),
                ('no_of_dependents', models.IntegerField(default=0)),
                ('income_annum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_term', models.IntegerField()),
                ('business_plan', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ml_approved', 'Auto Approved'), ('ml_rejected', 'Auto Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlanEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_analysis_rating', models.IntegerField()),
                ('business_model_rating', models.IntegerField()),
                ('financial_projections_rating', models.IntegerField()),
                ('management_team_rating', models.IntegerField()),
                ('risk_assessment_rating', models.IntegerField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('feedback', models.TextField()),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan_evaluation', to='sme.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('yoe', models.DateField()),
                ('industry', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('cibil_score', models.IntegerField()),
                ('residential_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commercial_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('luxury_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_asset_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('self_employed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sme_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='sme.sme'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
