# Generated by Django 5.0.3 on 2024-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_loanapplication_businessplanevaluation_sme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='bank_asset_value',
        ),
        migrations.RemoveField(
            model_name='sme',
            name='commercial_assets_value',
        ),
        migrations.RemoveField(
            model_name='sme',
            name='luxury_assets_value',
        ),
        migrations.RemoveField(
            model_name='sme',
            name='residential_assets_value',
        ),
        migrations.RemoveField(
            model_name='sme',
            name='self_employed',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_asset_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='commercial_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='luxury_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repay_prob',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='residential_assets_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='self_employed',
            field=models.BooleanField(default=False),
        ),
    ]
