# Generated by Django 5.0.3 on 2024-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0003_remove_sme_bank_asset_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplanevaluation',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='businessplanevaluation',
            name='overall_score',
            field=models.IntegerField(),
        ),
    ]
